# my own config
ZSH_THEME="random"

# emacs
function run_emacs
{
	emacsclient "$1" &
}
export EDITOR=emacsclient
export ALTERNATE_EDITOR=emacs
alias emacs="run_emacs"
alias edit="run_emacs"

export TERM=xterm-256color
j
# fix terminal key bugs
bindkey  "^[[1~"   beginning-of-line
bindkey  "^[[4~"   end-of-line

# useful alias
alias ll="ls -ahl"
alias dog="watch -n 1 -d"
alias ta="tmux a"
alias tn="tmux new"
alias tm="tmux attach || tmux new"