(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(flycheck-flake8-maximum-line-length 100)
 '(global-flycheck-mode t)
 '(package-selected-packages
   '(git-gutter-fringe+ git-gutter-fringe fringe-helper git-gutter+ git-gutter diff-hl browse-at-remote rainbow-mode rainbow-identifiers color-identifiers-mode 2048-game yasnippet-snippets writeroom-mode visual-fill-column treemacs-projectile treemacs-evil treemacs ht pfuture symon symbol-overlay string-inflection spaceline-all-the-icons powerline pippel pipenv password-generator spinner overseer org-category-capture alert log4e gntp org-cliplink org-brain nameless markdown-mode magit-svn magit-popup importmagic epc ctable concurrent deferred parent-mode helm-xref helm-purpose window-purpose imenu-list helm-org-rifle request helm-git-grep gitignore-templates gitignore-mode flyspell-correct pos-tip flycheck-package package-lint flycheck flx evil-textobj-line evil-org magit transient git-commit with-editor evil-lion iedit evil-goggles evil-cleverparens smartparens paredit anzu editorconfig doom-modeline shrink-path devdocs counsel-projectile projectile counsel swiper pkg-info epl company centered-cursor-mode blacken yasnippet packed f dash s memoize helm avy helm-core auto-complete popup org-plus-contrib hydra lv font-lock+ evil goto-chg undo-tree dotenv-mode bind-map bind-key async yapfify pyvenv pytest pyenv-mode py-isort py-autopep8 pip-requirements org-ref pdf-tools key-chord ivy tablist live-py-mode hy-mode dash-functional helm-pydoc helm-bibtex parsebib cython-mode csv-mode company-auctex company-anaconda biblio biblio-core auctex anaconda-mode pythonic ws-butler winum which-key volatile-highlights vi-tilde-fringe uuidgen use-package unfill toc-org spaceline smeargle restart-emacs rainbow-delimiters popwin persp-mode pcre2el paradox orgit org-projectile org-present org-pomodoro org-mime org-download org-bullets open-junk-file neotree mwim move-text mmm-mode material-theme markdown-toc magit-gitflow macrostep lorem-ipsum linum-relative link-hint indent-guide hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers highlight-indentation helm-themes helm-swoop helm-projectile helm-mode-manager helm-make helm-gitignore helm-flx helm-descbinds helm-company helm-c-yasnippet helm-ag google-translate golden-ratio gnuplot gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link gh-md fuzzy flyspell-correct-helm flycheck-pos-tip flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-ediff evil-args evil-anzu eval-sexp-fu elisp-slime-nav dumb-jump diminish define-word company-statistics column-enforce-mode clean-aindent-mode auto-yasnippet auto-highlight-symbol auto-dictionary auto-compile all-the-icons aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line ac-ispell)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
